CREATE TABLE IF NOT EXISTS products (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(128) NOT NULL UNIQUE,
	description VARCHAR(510) NOT NULL,
	price REAL NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	category VARCHAR(64) NOT NULL
)